config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root :to => 'homes#top'
  resources :books
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 validates :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 def index
  @book = Book.new
  @books = Book.all
 end 
 
 def create
  flash[:notice] = "Book was successfully created."
  @book = Book.new(book_params)
  if @book.save
  redirect_to book_path(@book.id)
  else
  @books = Book.all 
  render :index
  end
 end 
 
 def show
  @book = Book.find(params[:id])
 end
 
 def edit
  @book = Book.find(params[:id])
 end
 
 def update
  flash[:notice] = "Book was successfully updated."
  @book = Book.find(params[:id])
  if @book.update(book_params)
  redirect_to book_path(@book.id)
  else
  render :edit
  end
 end
 
 def destroy
  book = Book.find(params[:id])  # データ（レコード）を1件取得
  book.destroy  # データ（レコード）を削除
  redirect_to '/books'
 end

private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
  def top
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
    <h2><%= @book.errors.count %>error</h2>
    <% @book.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
<% end %>

<h1><strong>Editing book</strong></h1>
<%= form_with model: @book, local:true do |f| %>
  <h5>Title</h5>
  <%= f.text_field :title %>
  <h5>Body</h5>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show", book_path %> | <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1><strong>Books</strong></h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>
  
  <% @books.each do |book| %>
   <tr>
     <td><span><%= book.title %></span></td>
     <td><span><%= book.body %></span></td>
     <td><%= link_to "show", book_path(book.id) %></td>
     <td><%= link_to "edit", edit_book_path(book.id) %></td>
     <td><%= link_to "destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
   </tr>
  <% end %>
</table>

<% if @book.errors.any? %>
    <h2><%= @book.errors.count %>error</h2>
    <% @book.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
<% end %>

<h3><strong>New book</strong></h3>
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <h5>Title</h5>
  <%= f.text_field :title %>
  <h5>Body</h5>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
    <p id="notice">
     <%= flash[:notice] %>
    </p>
   <% end %>
<p><strong>Title :</strong></p><span><%= @book.title %></span>
<p><strong>Body :</strong></p><span><%= @book.body %></span>
<br>
<br>
<%= link_to "Edit", edit_book_path %> | <%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>

<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や<br>

印象を共有し交換することができます</p>

<span>
    <%= link_to "start", "/books" %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>